import Agra from "./Agra.jpg" 
import Ahmedabad from "../assets/Ahmedabad.jpg"    
import Ayodhya from "../assets/Ayodhya.jpg"    
import Bangalore from "../assets/Bangalore.jpg"    
import Banner from "../assets/Banner.jpg"    
import Banner2 from "../assets/Banner2.jpg"    
import Banner3 from "../assets/Banner3.jpeg"    
import Delhi from "../assets/Dehli.jpg"    
import Kutch from "../assets/Kutch.jpg"    
import Mumbai from "../assets/Mumbai.jpg"    
import Pune from "../assets/Pune.jpg"    
import Hyderabad from "../assets/Hyderabad.jpg"
import About from "../assets/About.jpg"
import Logo from "../assets/Logo.png"
import Banner4 from "../assets/Banner4.webp"
import ContactBanner from "../assets/ContactBanner.jpg"
export { Agra , Banner4, ContactBanner,  Ahmedabad ,Ayodhya ,Logo ,About, Bangalore , Banner , Banner2 , Banner3 , Delhi , Hyderabad , Mumbai , Kutch , Pune} 