import Agra from "./Agra.jpg" 
import Ahmedabad from "../assets/Ahmedabad.jpg"    
import Ayodhya from "../assets/Ayodhya.jpg"    
import Bangalore from "../assets/Bangalore.jpg"    
import Banner from "../assets/Banner.jpg"    
import Banner2 from "../assets/Banner2.jpg"    
import Banner3 from "../assets/Banner3.jpeg"    
import Delhi from "../assets/Dehli.jpg"    
import Kutch from "../assets/Kutch.jpg"    
import Mumbai from "../assets/Mumbai.jpg"    
import Pune from "../assets/Pune.jpg"    
import Tirupati from "../assets/Tirupati.jpg"
import Hyderabad from "../assets/Hyderabad.jpg"
import About from "../assets/About.jpg"
export { Agra ,  Ahmedabad ,Ayodhya ,About, Bangalore , Banner , Banner2 , Banner3 , Delhi , Hyderabad , Mumbai , Kutch , Pune , Tirupati } 